lego:
    resource: "@IdkLegoBundle/Resources/config/routing/routes.yml"
    prefix: /lego

lego_security:
    resource: 'Idk\LegoBundle\Controller\SecurityController'
    type:     annotation
    prefix:   /lego